
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-pod
  failurePolicy: Ignore
  name: mpod.kubesphere.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-tenant-phoenix-fearlesschenc-com-v1alpha1-workspaceclaim
  failurePolicy: Fail
  name: vworkspaceclaim.kubesphere.io
  rules:
  - apiGroups:
    - tenant.phoenix.fearlesschenc.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - workspaceclaims
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-tenant-phoenix-fearlesschenc-com-v1alpha1-networkpolicy
  failurePolicy: Fail
  name: vnetworkpolicy.kubesphere.io
  rules:
  - apiGroups:
    - networking.phoenix.fearlesschenc.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - networkpolicys
