# permissions for end users to view applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-viewer-role
rules:
- apiGroups:
  - workload.phoenix.fearlesschenc.com
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workload.phoenix.fearlesschenc.com
  resources:
  - applications/status
  verbs:
  - get
