# permissions for end users to view offlineapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: offlineapplication-viewer-role
rules:
- apiGroups:
  - workload.phoenix.fearlesschenc.com
  resources:
  - offlineapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workload.phoenix.fearlesschenc.com
  resources:
  - offlineapplications/status
  verbs:
  - get
