
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tenant.phoenix.fearlesschenc.com
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.phoenix.fearlesschenc.com
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tenant.phoenix.fearlesschenc.com
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.phoenix.fearlesschenc.com
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workload.phoenix.fearlesschenc.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.phoenix.fearlesschenc.com
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workload.phoenix.fearlesschenc.com
  resources:
  - offlineapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.phoenix.fearlesschenc.com
  resources:
  - offlineapplications/status
  verbs:
  - get
  - patch
  - update
