
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tenant.phoenix.fearlesschenc.com
  resources:
  - workspaceclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.phoenix.fearlesschenc.com
  resources:
  - workspaceclaims/status
  verbs:
  - get
  - patch
  - update
