# permissions for end users to view workspaceclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspaceclaim-viewer-role
rules:
- apiGroups:
  - tenant.phoenix.fearlesschenc.com
  resources:
  - workspaceclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenant.phoenix.fearlesschenc.com
  resources:
  - workspaceclaims/status
  verbs:
  - get
