
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    url: https://86996074da2a.ngrok.io/mutate-v1-pod
  failurePolicy: Fail
  name: mpod.kubesphere.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    url: https://55047b0a46ae.ngrok.io/mutate-tenant-phoenix-fearlesschenc-com-v1alpha1-workspaceclaim
  failurePolicy: Fail
  name: vworkspaceclaim.kubesphere.io
  rules:
  - apiGroups:
    - tenant.phoenix.fearlesschenc.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - workspaceclaims
