## Append samples you want in your CSV to this file as resources ##
resources:
- tenant_v1alpha1_workspace.yaml
- tenant_v1alpha1_cluster.yaml
- workload_v1alpha1_offlineapplication.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
