apiVersion: networking.phoenix.fearlesschenc.com/v1alpha1
kind: NetworkPolicy
metadata:
  name: networkpolicy-sample
spec:
  workspace: foo
  namespaceSelector:
    matchLabels:
      kubesphere.io/namespace: foo1
  from:
  - workspace: bar
    namespaceSelector:
      matchLabels:
        kubesphere.io/namespace: bar1
